#!/bin/sh
### BEGIN INIT INFO
# Provides:          ladaemon
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: <Enter a short description of the sortware>
# Description:       <Enter a long description of the software>
#                    <...>
#                    <...>
### END INIT INFO

# Author: root <naughtyboywx@yeah.net>
DAEMON=ladaemon
case "$1" in
    start)
        cd /opt/ladaemon
        sbin/$DAEMON -d
        ;;
    stop)
        pid=`pidof $DAEMON`
        if [ "X$pid" = "X" ]; then
            return 0
        fi
        kill -9 $pid
        RETVAL=$?
        exit "$RETVAL"
        ;;
    status)
        pid=`pidof $DAEMON`
        if [ "X$pid" = "X" ]; then
            echo "$DAEMON is dead"
        else
            echo "$DAEMON is alive, the pid is $pid"
        fi
        ;;
    *)
        echo "Usage: ladaemon {start|stop|status}" >&2
        exit 3
        ;;
esac

:
